apiVersion: v1
kind: Service
metadata:
  name: sa-webapp-mysql
  labels:
    app: sa-webapp
spec:
  ports:
    - port: 3306
  selector:
    app: sa-webapp
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sa-webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp-mysql
  labels:
    app: sa-webapp
spec:
  selector:
    matchLabels:
      app: sa-webapp
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sa-webapp
        tier: backend
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "toor"
            - name: MYSQL_DATABASE
              value: "sa_webapp"
            - name: MYSQL_USER
              value: "sa_user"
            - name: MYSQL_PASSWORD
              value: "sa_password"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
