apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sa-webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp
  labels:
    app: sa-webapp
spec:
  selector:
    matchLabels:
      app: sa-webapp
  template:
    metadata:
      labels:
        app: sa-webapp
        tier: backend
    spec:
      containers:
        - name: sa-webapp
          image: 1uka/sa-webapp:stateful
          imagePullPolicy: Always
          env:
            - name: SA_LOGIC_API_URL
              value: "http://sa-logic"
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_DATABASE
              value: "sa_webapp"
            - name: MYSQL_USER
              value: "sa_user"
            - name: MYSQL_PASSWORD
              value: "sa_password"
          ports:
            - containerPort: 8080

        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "toor"
            - name: MYSQL_DATABASE
              value: "sa_webapp"
            - name: MYSQL_USER
              value: "sa_user"
            - name: MYSQL_PASSWORD
              value: "sa_password"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
