apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - image: rinormaloku/sentiment-analysis-web-app:destroyable
        imagePullPolicy: Always
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 5
          initialDelaySeconds: 2
          successThreshold: 1
        readinessProbe:
          httpGet:  
            path: /health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          initialDelaySeconds: 30
          timeoutSeconds: 1