apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-logic
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
      - image: {{DOCKER_USER}}/sentiment-analysis-logic:{{TAG}}
        imagePullPolicy: Always
        name: sa-logic
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sa-logic
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: sa-logic