apiVersion: v1
kind: Service
metadata:
  name: sa-frontend-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: frontend.sa-cluster.1uka.me
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sa-frontend
